platform :ios, 7.0
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'AsyncImageView'
pod 'CRToast'
pod 'NSDate+TimeAgo'
pod 'FRDLivelyButton', '~> 1.0.0'
pod 'HMSegmentedControl'
pod 'ObjectiveRecord', '~> 1.5.0'
pod 'UIAlertView+Blocks'
pod 'UIActionSheet+Blocks'
pod 'UICKeyChainStore'
pod 'IAPHelper'
pod 'ReactiveCocoa'
pod 'ReactiveViewModel'
pod 'libextobjc'
pod 'Mantle'
pod 'Masonry'